import { Router } from 'express';
import { generateGameConceptAI, simulatePlaytestTurnAI } from '../services/gemini.js';
import { aiRateLimiter } from '../middleware/rateLimiter.js';
import { validateBody } from '../middleware/validate.js';
import { generateGameSchema, playtestStepSchema } from '../../shared/schema.js';

const router = Router();

// Apply AI rate limiter
router.use(aiRateLimiter);

// POST /api/ai/generate-concept - Generate complete game concept with Gemini AI
router.post('/generate-concept', validateBody(generateGameSchema), async (req, res) => {
  try {
    const input = req.validatedBody;
    console.log(`[AI Route] Generating game concept for ${input.civilization} (${input.category})`);

    const concept = await generateGameConceptAI(input);

    res.json({
      success: true,
      message: 'Game concept successfully generated by SanskritiPlay AI.',
      data: concept
    });
  } catch (err) {
    console.error('[AI Route] Error generating concept:', err);
    res.status(500).json({
      success: false,
      error: 'Failed to generate game concept. Please try again.',
      details: err.message
    });
  }
});

// POST /api/ai/playtest-step - Interactive turn simulation & tactical AI arbiter
router.post('/playtest-step', validateBody(playtestStepSchema), async (req, res) => {
  try {
    const { gameState, actionRequested, actionPayload } = req.validatedBody;
    
    const turnResult = await simulatePlaytestTurnAI(gameState, actionRequested, actionPayload);

    res.json({
      success: true,
      data: turnResult
    });
  } catch (err) {
    console.error('[AI Route] Error in playtest simulation:', err);
    res.status(500).json({
      success: false,
      error: 'Playtest simulation failed',
      details: err.message
    });
  }
});

export default router;
